# Generated by Django 5.0.1 on 2024-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('sobrenome', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
                ('email', models.TextField()),
                ('cep', models.TextField()),
                ('passworld', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.TextField()),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
